// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ovprthnlfbuzwjjhovrq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im92cHJ0aG5sZmJ1endqamhvdnJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExODU4MDEsImV4cCI6MjA2Njc2MTgwMX0.Io4N_BOdwnSFrhVpJz9ADUOgvRlS9EL78uNTYH-2NbA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});